//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarlordsMapEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WarlordsMapEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bridges {
            get {
                object obj = ResourceManager.GetObject("bridges", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap castles {
            get {
                object obj = ResourceManager.GetObject("castles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap forest {
            get {
                object obj = ResourceManager.GetObject("forest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;FractionList&gt;
        ///  &lt;fractions&gt;
        ///    &lt;Fraction name=&quot;Castle&quot;&gt;
        ///      &lt;buildings&gt;
        ///        &lt;building&gt;Guardhouse&lt;/building&gt;
        ///        &lt;building&gt;Armory&lt;/building&gt;
        ///        &lt;building&gt;Archers&apos; Tower&lt;/building&gt;
        ///        &lt;building&gt;Barracks&lt;/building&gt;
        ///        &lt;building&gt;Stables&lt;/building&gt;
        ///      &lt;/buildings&gt;
        ///    &lt;/Fraction&gt;
        ///    &lt;Fraction name=&quot;Rampart&quot;&gt;
        ///      &lt;buildings&gt;
        ///        &lt;building&gt;Dwarf Cottage&lt;/building&gt;
        ///        &lt;building&gt;Enchanted Spring&lt;/building&gt;
        ///        &lt;building&gt;Wizard Tower&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Fractions {
            get {
                return ResourceManager.GetString("Fractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grass {
            get {
                object obj = ResourceManager.GetObject("grass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hills {
            get {
                object obj = ResourceManager.GetObject("hills", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mountains {
            get {
                object obj = ResourceManager.GetObject("mountains", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap roads {
            get {
                object obj = ResourceManager.GetObject("roads", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ruin {
            get {
                object obj = ResourceManager.GetObject("ruin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;RuinsDataList&gt;
        ///
        ///	&lt;Ruins name=&quot;ruins&quot;&gt;
        ///		&lt;sprites&gt;
        ///			&lt;string&gt;ruin_1&lt;/string&gt;
        ///			&lt;string&gt;ruin_2&lt;/string&gt;
        ///			&lt;string&gt;temples_0&lt;/string&gt;
        ///		&lt;/sprites&gt;
        ///		&lt;action&gt;UnitsBattle&lt;/action&gt;
        ///		&lt;enemyUnits&gt;
        ///			&lt;string&gt;Axeman&lt;/string&gt;
        ///			&lt;string&gt;Pikeman&lt;/string&gt;
        ///			&lt;string&gt;Dwarf&lt;/string&gt;
        ///		&lt;/enemyUnits&gt;
        ///		&lt;resourceBonus&gt;
        ///			&lt;Resource&gt;
        ///				&lt;name&gt;gold&lt;/name&gt;
        ///				&lt;count&gt;5000&lt;/count&gt;
        ///			&lt;/Resource&gt;
        ///		&lt;/resourceBonus&gt;
        ///	&lt;/Ruins&gt;
        ///
        ///&lt;/RuinsDataList&gt;
        ///.
        /// </summary>
        internal static string Ruins {
            get {
                return ResourceManager.GetString("Ruins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap swamp {
            get {
                object obj = ResourceManager.GetObject("swamp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap temples {
            get {
                object obj = ResourceManager.GetObject("temples", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap water {
            get {
                object obj = ResourceManager.GetObject("water", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
